### ISSUE TITLE
Type theory resources

### ISSUE THREAD

**Issue by steveoni** [DavidTimms/loxdown#14]
Hi, I'm also following the same book for lox and also have my implementation in Typescript.
I just want to ask for any recommended resources you use to understand and implement the types system.

Thanks. great job

**Comment by DavidTimms** [comment]
Thanks Steve :+1: 

I didn't really use any books or other resources while implementing the typechecker. It was mostly just trial and error.

Most of the learning resources around the implementation of typecheckers focus on ML-style type systems, whereas with Loxdown I chose something more closely inspired by gradual type systems and set theory.

If you do want a more academic look at the topic, I've heard good things about [Types and Programming Languages by Benjamin C. Pierce](https://www.cis.upenn.edu/~bcpierce/tapl/), though I've not read it myself.

Good luck, and please do share what you create!
